### ISSUE TITLE
devtools::check() fails on compile in M1 Mac

### ISSUE THREAD

**Issue by kgoldfeld** [r-lib/devtools#2386]
I am not able to successfully run `devtools::check()` on my M1 Mac. In general, compiling with Mac's Xcode has been challenging, but I have been able to build packages using a `gfortran` `gcc` compiler, or a `llvm` `clang` compiler installed using `homebrew`. I have had to bypass the Xcode clang compiler.

But, it appears that it is not possible to use a `Makevars` file with `devtools::check()`, and so I am getting errors from the build process, which seem to be related to the `cmath` file. I've found others who have this problem but have not found a successful solution. Any ideas about how I can deal with this would be much appreciated since I currently can't use my M1 device to properly check my package before submission.

I've included the errors here, and below, I've included the case where I build using `gcc`:

```r
==> Rcpp::compileAttributes()

* Updated R/RcppExports.R

==> devtools::check()

ℹ Updating simstudy documentation
ℹ Loading simstudy
Writing NAMESPACE
Writing NAMESPACE
Writing simstudy-package.Rd
── Building ────────────────────────────────────────────────────────────────────────── simstudy ──
Setting env vars:
• CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
• CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
• CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
──────────────────────────────────────────────────────────────────────────────────────────────────
✓  checking for file ‘/Users/keith/git R projects/simstudy/DESCRIPTION’ ...
─  preparing ‘simstudy’: (395ms)
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to build vignettes
         -----------------------------------
─  installing *source* package ‘simstudy’ ...
   ** using staged installation
   ** libs
   clang++ -arch arm64 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c RcppExports.cpp -o RcppExports.o
   In file included from RcppExports.cpp:4:
   In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp.h:27:
   In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/RcppCommon.h:30:
   In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp/r/headers.h:66:
   In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:321:9: error: no member named 'signbit' in the global namespace
   using ::signbit;
         ~~^
   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:322:9: error: no member named 'fpclassify' in the global namespace
   using ::fpclassify;
         ~~^
   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:323:9: error: no member named 'isfinite' in the global namespace
   using ::isfinite;
         ~~^
   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:324:9: error: no member named 'isinf' in the global namespace
   using ::isinf;
         ~~^
   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:325:9: error: no member named 'isnan' in the global namespace
   using ::isnan;
         ~~^
   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:326:9: error: no member named 'isnormal' in the global namespace
   using ::isnormal;
         ~~^
   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:327:9: error: no member named 'isgreater' in the global namespace
   using ::isgreater;
         ~~^
   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:328:9: error: no member named 'isgreaterequal' in the global namespace
   using ::isgreaterequal;
         ~~^
   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:329:9: error: no member named 'isless' in the global namespace
   using ::isless;
         ~~^
   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:330:9: error: no member named 'islessequal' in the global namespace
   using ::islessequal;
         ~~^
   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:331:9: error: no member named 'islessgreater' in the global namespace
   using ::islessgreater;
         ~~^
   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:332:9: error: no member named 'isunordered' in the global namespace
   using ::isunordered;
         ~~^
   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:333:9: error: no member named 'isunordered' in the global namespace
   using ::isunordered;
         ~~^
   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:339:9: error: no member named 'abs' in the global namespace; did you mean 'fabs'?
   using ::abs;
         ~~^
   /usr/local/include/math.h:417:15: note: 'fabs' declared here
   extern double fabs(double);
                 ^
   In file included from RcppExports.cpp:4:
   In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp.h:27:
   In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/RcppCommon.h:30:
   In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp/r/headers.h:66:
   In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:644:26: error: no template named 'numeric_limits'
       bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits),
                            ^
   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:644:60: error: no template named 'numeric_limits'
       bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits),
                                                              ^
   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:645:18: error: no template named 'numeric_limits'
       int _Bits = (numeric_limits<_IntT>::digits - numeric_limits<_FloatT>::digits)>
                    ^
   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:645:50: error: no template named 'numeric_limits'
       int _Bits = (numeric_limits<_IntT>::digits - numeric_limits<_FloatT>::digits)>
                                                    ^
   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:650:17: error: no template named 'numeric_limits'
     static_assert(numeric_limits<_FloatT>::radix == 2, "FloatT has incorrect radix");
                   ^
   fatal error: too many errors emitted, stopping now [-ferror-limit=]
   20 errors generated.
   make: *** [RcppExports.o] Error 1
   ERROR: compilation failed for package ‘simstudy’
─  removing ‘/private/var/folders/jr/19fz7v9976gbf62sf66f7zz40000gq/T/Rtmp6tAmY8/Rinst1835c5e61da95/simstudy’
         -----------------------------------
   ERROR: package installation failed

Error: System command 'R' failed, exit status: 1, stdout + stderr:
E> * checking for file ‘/Users/keith/git R projects/simstudy/DESCRIPTION’ ... OK
E> * preparing ‘simstudy’:
E> * checking DESCRIPTION meta-information ... OK
E> * cleaning src
E> * installing the package to build vignettes
E>       -----------------------------------
E> * installing *source* package ‘simstudy’ ...
E> ** using staged installation
E> ** libs
E> clang++ -arch arm64 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c RcppExports.cpp -o RcppExports.o
E> In file included from RcppExports.cpp:4:
E> In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp.h:27:
E> In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/RcppCommon.h:30:
E> In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp/r/headers.h:66:
E> In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:321:9: error: no member named 'signbit' in the global namespace
E> using ::signbit;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:322:9: error: no member named 'fpclassify' in the global namespace
E> using ::fpclassify;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:323:9: error: no member named 'isfinite' in the global namespace
E> using ::isfinite;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:324:9: error: no member named 'isinf' in the global namespace
E> using ::isinf;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:325:9: error: no member named 'isnan' in the global namespace
E> using ::isnan;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:326:9: error: no member named 'isnormal' in the global namespace
E> using ::isnormal;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:327:9: error: no member named 'isgreater' in the global namespace
E> using ::isgreater;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:328:9: error: no member named 'isgreaterequal' in the global namespace
E> using ::isgreaterequal;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:329:9: error: no member named 'isless' in the global namespace
E> using ::isless;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:330:9: error: no member named 'islessequal' in the global namespace
E> using ::islessequal;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:331:9: error: no member named 'islessgreater' in the global namespace
E> using ::islessgreater;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:332:9: error: no member named 'isunordered' in the global namespace
E> using ::isunordered;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:333:9: error: no member named 'isunordered' in the global namespace
E> using ::isunordered;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:339:9: error: no member named 'abs' in the global namespace; did you mean 'fabs'?
E> using ::abs;
E>       ~~^
E> /usr/local/include/math.h:417:15: note: 'fabs' declared here
E> extern double fabs(double);
E>               ^
E> In file included from RcppExports.cpp:4:
E> In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp.h:27:
E> In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/RcppCommon.h:30:
E> In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp/r/headers.h:66:
E> In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:644:26: error: no template named 'numeric_limits'
E>     bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits),
E>                          ^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:644:60: error: no template named 'numeric_limits'
E>     bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits),
E>                                                            ^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:645:18: error: no template named 'numeric_limits'
E>     int _Bits = (numeric_limits<_IntT>::digits - numeric_limits<_FloatT>::digits)>
E>                  ^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:645:50: error: no template named 'numeric_limits'
E>     int _Bits = (numeric_limits<_IntT>::digits - numeric_limits<_FloatT>::digits)>
E>                                                  ^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:650:17: error: no template named 'numeric_limits'
E>   static_assert(numeric_limits<_FloatT>::radix == 2, "FloatT has incorrect radix");
E>                 ^
E> fatal error: too many errors emitted, stopping now [-ferror-limit=]
E> 20 errors generated.
E> make: *** [RcppExports.o] Error 1
E> ERROR: compilation failed for package ‘simstudy’
E> * removing ‘/private/var/folders/jr/19fz7v9976gbf62sf66f7zz40000gq/T/Rtmp6tAmY8/Rinst1835c5e61da95/simstudy’
E>       -----------------------------------
E> ERROR: package installation failed

 Stack trace:

 1. devtools::check(, check_dir = dirname(getwd()))
 2. withr::with_envvar(pkgbuild::compiler_flags(FALSE), action = "pre ...
 3. base:::force(code)
 4. pkgbuild::build(pkg$path, tempdir(), args = build_args, quiet = q ...
 5. withr::with_temp_libpaths(rcmd_build_tools(options$cmd, c(options ...
 6. base:::force(code)
 7. pkgbuild:::rcmd_build_tools(options$cmd, c(options$path, options$ ...
 8. pkgbuild:::with_build_tools(callr::rcmd_safe(..., env = env,  ...
 9. callr::rcmd_safe(..., env = env, spinner = FALSE, show = FALSE,  ...
 10. callr:::run_r(options)
 11. base:::with(options, with_envvar(env, do.call(processx::run,  ...
 12. base:::with.default(options, with_envvar(env, do.call(processx::r ...
 13. base:::eval(substitute(expr), data, enclos = parent.frame())
 14. base:::eval(substitute(expr), data, enclos = parent.frame())
 15. callr:::with_envvar(env, do.call(processx::run, c(list(bin, args  ...
 16. base:::force(code)
 17. base:::do.call(processx::run, c(list(bin, args = real_cmdargs,  ...
 18. (function (command = NULL, args = character(), error_on_status = TRUE,  ...
 19. throw(new_process_error(res, call = sys.call(), echo = echo,  ...

 x System command 'R' failed, exit status: 1, stdout + stderr:
E> * checking for file ‘/Users/keith/git R projects/simstudy/DESCRIPTION’ ... OK
E> * preparing ‘simstudy’:
E> * checking DESCRIPTION meta-information ... OK
E> * cleaning src
E> * installing the package to build vignettes
E>       -----------------------------------
E> * installing *source* package ‘simstudy’ ...
E> ** using staged installation
E> ** libs
E> clang++ -arch arm64 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c RcppExports.cpp -o RcppExports.o
E> In file included from RcppExports.cpp:4:
E> In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp.h:27:
E> In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/RcppCommon.h:30:
E> In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp/r/headers.h:66:
E> In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:321:9: error: no member named 'signbit' in the global namespace
E> using ::signbit;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:322:9: error: no member named 'fpclassify' in the global namespace
E> using ::fpclassify;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:323:9: error: no member named 'isfinite' in the global namespace
E> using ::isfinite;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:324:9: error: no member named 'isinf' in the global namespace
E> using ::isinf;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:325:9: error: no member named 'isnan' in the global namespace
E> using ::isnan;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:326:9: error: no member named 'isnormal' in the global namespace
E> using ::isnormal;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:327:9: error: no member named 'isgreater' in the global namespace
E> using ::isgreater;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:328:9: error: no member named 'isgreaterequal' in the global namespace
E> using ::isgreaterequal;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:329:9: error: no member named 'isless' in the global namespace
E> using ::isless;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:330:9: error: no member named 'islessequal' in the global namespace
E> using ::islessequal;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:331:9: error: no member named 'islessgreater' in the global namespace
E> using ::islessgreater;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:332:9: error: no member named 'isunordered' in the global namespace
E> using ::isunordered;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:333:9: error: no member named 'isunordered' in the global namespace
E> using ::isunordered;
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:339:9: error: no member named 'abs' in the global namespace; did you mean 'fabs'?
E> using ::abs;
E>       ~~^
E> /usr/local/include/math.h:417:15: note: 'fabs' declared here
E> extern double fabs(double);
E>               ^
E> In file included from RcppExports.cpp:4:
E> In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp.h:27:
E> In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/RcppCommon.h:30:
E> In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp/r/headers.h:66:
E> In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:644:26: error: no template named 'numeric_limits'
E>     bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits),
E>                          ^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:644:60: error: no template named 'numeric_limits'
E>     bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits),
E>                                                            ^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:645:18: error: no template named 'numeric_limits'
E>     int _Bits = (numeric_limits<_IntT>::digits - numeric_limits<_FloatT>::digits)>
E>                  ^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:645:50: error: no template named 'numeric_limits'
E>     int _Bits = (numeric_limits<_IntT>::digits - numeric_limits<_FloatT>::digits)>
E>                                                  ^
E> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:650:17: error: no template named 'numeric_limits'
E>   static_assert(numeric_limits<_FloatT>::radix == 2, "FloatT has incorrect radix");
E>                 ^
E> fatal error: too many errors emitted, stopping now [-ferror-limit=]
E> 20 errors generated.
E> make: *** [RcppExports.o] Error 1
E> ERROR: compilation failed for package ‘simstudy’
E> * removing ‘/private/var/folders/jr/19fz7v9976gbf62sf66f7zz40000gq/T/Rtmp6tAmY8/Rinst1835c5e61da95/simstudy’
E>       -----------------------------------
E> ERROR: package installation failed 

Execution halted

Exited with status 1.
```

Here is the successful buildd code

```r
==> Rcpp::compileAttributes()

* Updated R/RcppExports.R

==> R CMD INSTALL --preclean --no-multiarch --with-keep.source simstudy

* installing to library ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library’
* installing *source* package ‘simstudy’ ...
** using staged installation
/usr/local/gfortran/bin/g++ -fopenmp -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include   -fPIC  -g -O3 -Wall -pedantic -std=c++11 -mtune=native -pipe -c RcppExports.cpp -o RcppExports.o
** libs
/usr/local/gfortran/bin/g++ -fopenmp -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include   -fPIC  -g -O3 -Wall -pedantic -std=c++11 -mtune=native -pipe -c srcRcpp.cpp -o srcRcpp.o
In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp/Vector.h:54,
                 from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp.h:40,
                 from srcRcpp.cpp:1:
/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp/vector/traits.h: In function ‘Rcpp::IntegerVector clipVec(Rcpp::IntegerVector, Rcpp::IntegerVector, Rcpp::IntegerVector)’:
/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp/vector/traits.h:46:60: warning: ‘xid’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   46 |                 inline proxy ref(R_xlen_t i) { return start[i] ; }
      |                                                       ~~~~~^
srcRcpp.cpp:68:7: note: ‘xid’ was declared here
   68 |   int xid;
      |       ^~~
/usr/local/gfortran/bin/g++ -fopenmp -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o simstudy.so RcppExports.o srcRcpp.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/00LOCK-simstudy/00new/simstudy/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (simstudy)
```

**Comment by jimhester** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)

I am pretty sure there are a number of people with M1 macs that are able to compile this with the Xcode tools. Hopefully one of them will see your question and be able to suggest a solution.

**Comment by kgoldfeld** [comment]
OK - thanks. I'll try that - but it has been really hard to find any solution - been struggling with this for weeks. Definitely not the fun part or `R` :).

**Comment by gaborcsardi** [comment]
I don't think it is not worth fighting the default R setup on macOS. A lot of people are using the default compilers, and this setup works very well. So I would remove/unlink the compilers that you installed from brew, and install gfortran from https://mac.r-project.org/libs-arm64/ like the docs at the bottom of that page suggest:

```
curl -O https://mac.r-project.org/libs-arm64/gfortran-f51f1da0-darwin20.0-arm64.tar.gz
sudo tar fxz gfortran-f51f1da0-darwin20.0-arm64.tar.gz -C /
```

You don't need to create any `Makevars` files, either, so if you created some, remove/rename them.

If you run into problems, please ask on community.rstudio.com or on the R-sig-mac mailing list. Feel free to ping me (`@Gabor`) on community.rstudio.com.

**Comment by kgoldfeld** [comment]
I would love to use the default, and I only turned these other options, because the default compilers just were not working. I spent an incredible amount of time trying to get things to work - but I'm happy to give this a shot if you think it will do the trick.  Thanks.

**Comment by gaborcsardi** [comment]
It will definitely do the trick. I am using the defaults on two machines, and so does everyone I know.

**Comment by kgoldfeld** [comment]
That'll be awesome - I'll let you know if it works.

**Comment by lionel-** [comment]
I don't know if my setup on M1 is state of the art but I have this in Makevars to compile to x86:

```
CC = clang -target x86_64-apple-macos10.13
CXX = clang++ -target x86_64-apple-macos10.13
CXX11 = clang++ -target x86_64-apple-macos10.13
```

So not everyone you know @gaborcsardi ;)

**Comment by gaborcsardi** [comment]
> So not everyone you know @gaborcsardi ;)

I meant the people using the arm64 build. :P

**Comment by lionel-** [comment]
Actually I just removed the `target` flags and I can still compile packages, so these are now out of my config. Not sure what has changed since the last time I tried this but I'm happy that my setup has become simpler.

**Comment by kgoldfeld** [comment]
Just to be clear about the defaults - I have installed Xcode but without independently loading the command line tools with `xcode-select --install`, because that creates problems with Stan. But, I understand that just by downloading xcode that already includes the command line tools.

**Comment by gaborcsardi** [comment]
Yes. I have the command line tools, and don't have Xcode, but Xcode includes the command line tools. CRAN has clang 12.x, and I have clang 13.x, both should work and so should xcode 12.x and 13.x.

**Comment by kevinushey** [comment]
You might also want to use:

```
sudo xcode-select -s /Library/Developer/CommandLineTools
```

to ensure that clang uses the "command line tools" version of the standard library headers, rather than the Xcode version. (I've had trouble using the Xcode-bundled version with R)

**Comment by gaborcsardi** [comment]
@kevinushey What kind of problems specifically? They are literally the same compilers on my system:

```
❯ clang --version
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: arm64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

~
❯ /Library/Developer/CommandLineTools/usr/bin/clang --version
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: arm64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Do they use different header files?

**Comment by kevinushey** [comment]
That's what it seemed like... or, it might be a holdover from R 3.6 where R's Makeconf had something like:

```
CPPFLAGS = -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include
```

I don't remember the details; I just remember forcing the use of `/Library/Developer/CommandLineTools` avoided some compilation issues I saw previously.

**Comment by gaborcsardi** [comment]
Yeah, there is nothing like that for R 4.1, so I would guess that this is now fixed. I can install packages with C, C++ and Fortran code using the Xcode compilers just fine.

**Comment by kevinushey** [comment]
Looking a bit more closely at the compiler output:

```
E> /usr/local/include/math.h:417:15: note: 'fabs' declared here
E> extern double fabs(double);
E>               ^
```

The issue is most likely that custom headers have been installed to `/usr/local/include`, and because R uses `-I/usr/local/include` those headers are overriding the system headers.

I'm not sure what would've installed headers into `/usr/local/include` but overriding the system headers there is IMHO bad form.

**Comment by gaborcsardi** [comment]
CRAN's x86_64 R uses `/usr/local/include` for system libs, but I think that is independent of xcode vs command line tools.

**Comment by kgoldfeld** [comment]
So, I installed `gfortran` as suggested (and removed `Makevars` and this is my current situation:

```
keith$ clang --version
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: arm64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

```
keith$ xcode-select -p
/Library/Developer/CommandLineTools
```

And here is my current $PATH:

```
keith$ echo $PATH
/opt/R/arm64/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

But I am still getting errors, which I can share. Should I move this discussion to another forum, or continue here? 

Here is just a sample of the error messages:

```r
==> Rcpp::compileAttributes()

* Updated R/RcppExports.R

==> R CMD INSTALL --no-multiarch --with-keep.source simstudy

* installing to library ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library’
* installing *source* package ‘simstudy’ ...
** using staged installation
clang++ -arch arm64 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
** libs
In file included from RcppExports.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp.h:27:
In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/RcppCommon.h:30:
In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp/r/headers.h:66:
In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:321:9: error: no member named 'signbit' in the global namespace
using ::signbit;
```

**Comment by gaborcsardi** [comment]
Can you compile other packages?

**Comment by kgoldfeld** [comment]
If the package does not include RCPP code, I can install from source, but if it uses RCPP, then I get the same errors as when I try to build `simstudy`.

Here is my clang version:

```
% clang --version
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: arm64-apple-darwin20.6.0
```

And command line tools version:

```
% pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 13.0.0.0.1.1630607135
```

I just reinstalled Rcpp (as well as all the other Rccp-related packages I had installed). I also created the directory for a user package library. Should all of the packages I install go there (including simstudy)?

**Comment by gaborcsardi** [comment]
Which clang is this? Can you run `which clang`? Did you set up its target manually?

This is what I have:
```
❯ clang --version
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: arm64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by kgoldfeld** [comment]
Yes - the packages are now installing by default to `/Users/keith/Library/R/arm64/4.1/library`. So that's good (Should I just manually move all my user loaded packages to this directory? Or just reinstall them?)

I did *not* set up the target manually. Here are the results of `which clang`:

```
% which clang
/usr/bin/clang
```

**Comment by gaborcsardi** [comment]
It is possible that your older command line tools are not compatible with the compiler in xcode. Somewhat surprising, though. In any case you can try using the xcode compiler:

```
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer/
```

**Comment by kgoldfeld** [comment]
Still same error. Should I delete and re-install xcode and command line tools?

**Comment by gaborcsardi** [comment]
Yeah, it is nice to have a clean state. You can also reinstall R.

**Comment by kevinushey** [comment]
I still think the issue is ultimately caused by system headers (like math.h) in /use/local/include.

**Comment by kgoldfeld** [comment]
Any fix for those system headers?

**Comment by gaborcsardi** [comment]
There should not be system headers there. Do you know why they are there? Can you moved them aside?

**Comment by kgoldfeld** [comment]
Yes - they are there - not sure why they are since I didn't put them there - but they are links:

```
% ls -la math.h
lrwxr-xr-x  1 root  wheel  70 Apr  8  2021 math.h -> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/math.h
```

**Comment by kgoldfeld** [comment]
I removed the header links from `/usr/local/include` at everything is working! My guess is that when I installed the third-party version of `gcc`, it installed those header files in the directory.
